import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TransactionProvider } from "@/components/context/context";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster position="top-right" reverseOrder={false} />
      <TransactionProvider>
        <body className={inter.className}>{children}</body>
      </TransactionProvider>
    </html>
  );
}
